# Generated by Django 3.0.3 on 2020-07-02 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='author', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
